### ISSUE TITLE
Coming soon, need help?

### ISSUE THREAD

**Issue by JeromeK13** [surrealdb/surrealdb.py#1]
Hey Guys

Im an DBA with a big love for python. I expected to find some code already here, since on the website it says "coming soon".
Are you already working on this in an other repo or is there really nothing so far? Would also like to contribute some of my time to the project.

Greets
Jerome

**Comment by CaedenPH** [comment]
+ 2 for helping

**Comment by aurelion314** [comment]
+1. Hugely excited about SurrealDB. Willing to help as well.

**Comment by iot-resister** [comment]
+1 willing to help as well!

**Comment by lukehodges** [comment]
ill help

**Comment by CaedenPH** [comment]
It seems like surreal plans to write the sdk in rust due to time efficiency. However, due to the long wait time it may be an idea to create an unofficial surrealdb wrapper for python. Let me know what you think, we can discuss on the official surrealdb discord server here

https://surrealdb.com/discord

**Comment by cruzanstx** [comment]
I'm excited for the python and go drivers for this. Do we have a road map for what needs to be implemented/worked through to get the surrealdb driver / (restful/ws) wrappers in place to allow for direct python interaction with the surreal db?

**Comment by tsunyoku** [comment]
as an update for everyone, a client for surreal's HTTP API has now been pushed to main. there is also a PR in review for implementing the websocket API: https://github.com/surrealdb/surrealdb.py/pull/6

the package is currently not on PyPI, so if you want to use it now i suggest cloning the repo (although waiting will be better!). once the websocket PR is merged, i will work with Tobie to get the package up on PyPI.

**Comment by tobiemh** [comment]
Hi @JeromeK13 , @Natgho , @CaedenPH , @aurelion314 , @iot-resister , @lukehodges - thanks for your interest in the SurrealDB Python integration. The community is amazing!

I've just merged the first 2 PRs from @tsunyoku 👍😀 to get this integration off the ground.

Would love all suggestions, ideas, PRs, or any contribution!

**Comment by MaoMaoCake** [comment]
I've added some examples for using the HTTPClient it should be merged soon

**Comment by Salaah01** [comment]
This project sound really interesting. Count me in!

**Comment by realabja** [comment]
Count me also in!

**Comment by tobiemh** [comment]
Hey everyone! Just going to close this issue now, as a (as you probably already know) SurrealDB Python library is now available. Documentation should be available soon too!

Thanks to everyone involved in getting this to where it is now 😀👏🚀!

**Comment by lukehodges** [comment]
ill do documentation

**Comment by tsunyoku** [comment]
> ill do documentation

documentation is already in progress :P

**Comment by lukehodges** [comment]
fudge
