### ISSUE TITLE
Feature: Python SDK to support SurrealDB 2.x

### ISSUE THREAD

**Issue by martinholovsky** [surrealdb/surrealdb.py#115]
### Is your feature request related to a problem?

Current surrealdb.py does not support SurrealDB 2.x
Even mentioned on official site: https://surrealdb.com/docs/sdk/python

### Describe the solution

Update Python SDK to support for SurrealDB 2.x

### Alternative methods

n/a we use python on backend

### SurrealDB version

2.0.4

### surrealdb.py version

0.3.2

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Deutscher775** [comment]
It does support 2.x, but in a limited way. For example: only Root-Authentication seems to be supported and leaves Namespace and Database-Authentication behind. For now you could use [Maxwell Flitton's surreal-lite.py](https://github.com/maxwellflitton/surreal-lite-py) which does support these methods.

**Comment by lfnovo** [comment]
Is there any estimate on when this is coming?

**Comment by vadim-su** [comment]
Yeah, it will be great to get the full functionality of v2

**Comment by Deutscher775** [comment]
> Is there any estimate on when this is coming?

no sadly there is no estimate

**Comment by lfnovo** [comment]
I don't get it. Python is the largest, strongest AI community. This is literally the folks that would be excited about an AI-friendly database and we don't get even an estimate on support for a version that has been released for months?

**Comment by tobiemh** [comment]
Hi @lfnovo,  @Deutscher775, @vadim-su, @martinholovsky 👋  the latest version of the Python SDK has been completely re-written and now supports SurrealDB 2.0. Version `0.4.1` available on [PyPI here](https://pypi.org/project/surrealdb/) now makes use of a native Python with binary communication with remote databases, and support for embedded database usage. The native Python library now has support for custom types, including datetimes, durations, decimals, geojson types, Record IDs, ranges, and tables 🎉.

We're working on improved documentation at the moment, and will have an update soon!

**Comment by lfnovo** [comment]
@tobiemh Alright man! Now we are talking!! I am going to pretend I am important and my wish got granted after 12 hours :)
