### ISSUE TITLE
ETA..?

### ISSUE THREAD

**Issue by gnat** [surrealdb/surrealdb.py#2]
Very interested in trying out SurrealDB using Python on ASGI (for me, Sanic). Feels like it could be a perfect match.

Any early release for this driver coming out soon? Would it be possible to get a preview?

Also, this is planned to be an `asyncio` based connector, correct? :sweat_smile: 

I feel like there's a decent number of people waiting for this and ready to help out, too, if needed.

**Comment by tsunyoku** [comment]
please see https://github.com/surrealdb/surrealdb.py/issues/1#issuecomment-1250327569

**Comment by tobiemh** [comment]
Hi @gnat this is being worked on quickly - and should be coming really soon!
