### ISSUE TITLE
Line length

### ISSUE THREAD

**Issue by CaedenPH** [surrealdb/surrealdb.py#21]
What should the code line length be? `pep-8` suggests `79` characters, black defaults to `88`, what would you guys suggest?

**Comment by realabja** [comment]
So 88 I vote

**Comment by realabja** [comment]
So 88 I vote

**Comment by sam-kenney** [comment]
I'd also lean towards 88, one less line of config and all

**Comment by coldino** [comment]
79 leads to harder to read code in my opinion.
100+ is okay for private projects, but 88 is a happy medium for the best mix of accessibility and readability for all.

**Comment by iot-resister** [comment]
What about black? https://github.com/psf/black

**Comment by tsunyoku** [comment]
> What about black? https://github.com/psf/black

we're already using black, and i don't plan on changing the line length of black unless most people think it should. from what i gather, most are suggesting ~88 and hence i will not change it

**Comment by tobiemh** [comment]
I'll close this issue for now as it seems most people think `88` is a good number. Also if black defaults to `88`, then that should be fine for the moment 👍😀!
