### ISSUE TITLE
Library is unusable from PyPi. Please upload new version

### ISSUE THREAD

**Issue by TudorAndrei** [surrealdb/surrealdb.py#32]
A new version needs to be uploaded to PyPi that includes the fix in #26 . 

Otherwise, authentication is impossible.

Workaround: install with `pip install git+https://github.com/surrealdb/surrealdb.py.git`

**Comment by radu-pythia** [comment]
Yes, please! This is really frustrating.

**Comment by TudorAndrei** [comment]
Closed the issue, as the library has been updated.
