### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Ce11an** [surrealdb/surrealdb.py#40]
As discussed on https://github.com/surrealdb/surrealdb.py/issues/39, it would be advantageous for the project to implement issue templates for the following categories: Bug Reports, Feature Requests, and Documentation.

I propose that the templates should be formatted similarly to the [surrealdb](https://github.com/surrealdb/surrealdb/tree/main/.github/ISSUE_TEMPLATE) repository and include additional information related to Python. This may include the version of Python, surrealdb.py, surrealdb, the operating system (e.g. Linux), and the installation source (pip or source).

Let me know your thoughts. Thank you. 😄

**Comment by AlexFrid** [comment]
Closing this as the PR was merged
