### ISSUE TITLE
Improve code formatting - `ruff` and `mypy`

### ISSUE THREAD

**Issue by Ce11an** [surrealdb/surrealdb.py#41]
As per the discussion on https://github.com/surrealdb/surrealdb.py/issues/39, we can implement [ruff](https://github.com/charliermarsh/ruff) for code formatting in addition to black. The proposed ruff configuration is as follows:

- isort, which is compatible with black
- pydocstyle, with a preference for Google style but open to suggestions
- flake8
- By using ruff, we won't need the [.flake8](https://github.com/surrealdb/surrealdb.py/blob/main/.flake8) file. Additionally, ruff works well with pre-commit hooks.

We should also include [mypy](https://github.com/python/mypy) for type-checking in the project.

Please let me know your thoughts. Thank you 😄

**Comment by AlexFrid** [comment]
This all sounds good, closing this issue as the PR for the suggested changes has been merged
