### ISSUE TITLE
Adding edge with time gives error

### ISSUE THREAD

**Issue by unidesigner** [surrealdb/surrealdb.py#44]
I'm trying to add an edge between objects. As there is no direct API call, I'm trying to use a query:
```
query = f"""RELATE table:A->part_of->table:B SET time.written = time::now();"""
response = await client.execute(query)
```
Give a `
NameError: name 'time' is not defined
`
I'd expect that this is resolved in the database directly?

**Comment by AlexFrid** [comment]
Thanks for bringing this up, this is fixed now.

When you do:
```python
query = f"""RELATE table:A->part_of->table:B SET time.written = time::now();"""
response = await db.query(query)
```
it returns:
```
[{'result': [{'id': 'part_of:xno3azkxoh3rzau6e55n',
    'in': 'table:A',
    'out': 'table:B',
    'time': {'written': '2023-03-31T13:07:26.118577Z'}}],
  'status': 'OK',
  'time': '706.458µs'}]
```
I'll therefore close this issue.
Happy discuss more in discord.
