### ISSUE TITLE
Bug: Specific UNICODE string error?

### ISSUE THREAD

**Issue by keigon** [surrealdb/surrealdb.py#56]
### Describe the bug

When I try to enter a specific unicode string into surrealDB using the python client, I get a parse error.

```
import asyncio
from surrealdb import Surreal

async def test():
    """Example of how to use the SurrealDB client."""
    async with Surreal("ws://localhost:8000/rpc") as db:
        await db.signin({"user": "root", "pass": "root"})
        await db.use("test", "test")
        await db.create(
            "person",
            {
                "user": "제10",
            },
        )

if __name__ == "__main__":
    import asyncio

    asyncio.run(test())

```

Result:
```
  File "......database/test.py", line 9, in test
    await db.create(
  File "....../lib/python3.9/site-packages/surrealdb/ws.py", line 482, in create
    success: ResponseSuccess = _validate_response(
  File "....../lib/python3.9/site-packages/surrealdb/ws.py", line 161, in _validate_response
    raise exception(response.message)
surrealdb.ws.SurrealPermissionException: Parse error
```

Errors occur on strings like "제10", "가1234"

### Steps to reproduce

[[package]]
name = "surrealdb"
version = "0.3.0"

### Expected behaviour

Expecting a normal DB INSERT

### SurrealDB version

1.0.0-beta.9+20230402.5eafebd for macos on aarch64

### surrealdb.py version

0.3.0

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexFrid** [comment]
Thanks for letting us know about this bug, it has been fixed now, and a new release 0.3.1 is out on PyPi
