### ISSUE TITLE
Documentation: There is methods names difference on main website

### ISSUE THREAD

**Issue by burhankhanzada** [surrealdb/surrealdb.py#61]
### As you can see in below image at heading its saying `db.merge` and in the code snippet its saying `db.change` also for `db.patch` title its showing `db.modify` which confuses whats the real name to used those methods

![Screen Shot 2023-04-29 at 3 22 31 AM](https://user-images.githubusercontent.com/18241005/235264044-8b3af6b6-7b55-458b-a68f-d4bf48e3750e.jpg)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexFrid** [comment]
Thanks for this issue. We'll update the docs.
The correct method is in the header.

**Comment by unidesigner** [comment]
I just ran into an issue where the `merge` function does not work in the websocket client. And it's not implemented for the http client. Maybe this could be fixed at the same time.
