### ISSUE TITLE
Bug: Can't insert option as None

### ISSUE THREAD

**Issue by alanxoc3** [surrealdb/surrealdb.py#74]
### Describe the bug

Here is an example:

```
result = await db.query(f'''
  INSERT INTO list {{
    name: $name,
    desc: $desc,
  }}
''', {"name": "hello", "desc": None})
```

Where the desc column is type option<string>.

I'd expect "None" in python to evaluate to the option empty value, but I get this error message:

```
[{'result': 'Found NULL for field `description`, with record `...`, but expected a option<string>', 'status': 'ERR', 'time': '234.712µs'}]
```

### Steps to reproduce

See "describe bug".

### Expected behaviour

See "describe bug".

### SurrealDB version

surreal 1.0

### surrealdb.py version

python 3.11.5 - surrealdb lib 0.3.1

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellflitton** [comment]
Hey @alanxoc3 sorry for the late reply, can you provide the schema that you have for the table you're trying to insert into as right now you're expecting a `option<string>`.

**Comment by AlexFrid** [comment]
Also not exactly sure what the bug is here @alanxoc3 
None in Python gets translated to `NULL` in SurrealDB, not sure why you're expecting `option<string>` 🤔

**Comment by CosmKiwi** [comment]
Looks like a database bug/limitation, because if I run this query in Surrealist, I get the same error:

`create my_table set address = null;`

Looks like you can't set fields as null in a schemafull table? SurrealDB version 1.1.1

**Comment by AlexFrid** [comment]
hey @CosmKiwi, yeah there seems to be a bug with SurrealDB itself, doing this will however give you the expected results:
```sql
define field addess on my_table type option<string | null> default null;
```

**Comment by AlexFrid** [comment]
@alanxoc3 @CosmKiwi closing this as its not an issue with Python but a SurrealQL thing.
Currently our `null` is a value whereas `none` is not.

Doing just `option<string>` is saying its string field or no field.
Whereas `option<string | null>` is saying its a string field or field with a null value
