### ISSUE TITLE
Bug: did you publish the latest 0.3.2 version ?

### ISSUE THREAD

**Issue by happysalada** [surrealdb/surrealdb.py#84]
### Describe the bug

trying to poetry add surrealdb uses 0.3.1

### Steps to reproduce

- poetry add surrealdb
- using 0.3.2 in the pyproject.toml will give
```
Because project depends on surrealdb (^0.3.2) which doesn't match any versions, version solving failed.
```

### Expected behaviour

poetry add surrealdb adds 0.3.2 latest

### SurrealDB version

1.0.0

### surrealdb.py version

0.3.1

### Contact Details

github.opt547@simplelogin.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TudorAndrei-Pythia** [comment]
It's not released on [pypi](https://pypi.org/project/surrealdb/#history)

**Comment by AlexFrid** [comment]
We had some issues with PyPi that took some time to resolve, but it's published now.
